package br.edu.imepac.message.manager;

import br.edu.imepac.message.manager.entities.Contact;
import br.edu.imepac.message.manager.views.contacts.ContactAddForm;
import br.edu.imepac.message.manager.views.contacts.ContactListForm;
import br.edu.imepac.message.manager.views.contacts.ContactUpdateForm;
import br.edu.imepac.message.manager.views.messages.MessageListForm;
import br.edu.imepac.message.manager.views.messages.MessageSendForm;

public class MainDesktop extends javax.swing.JFrame {

    /**
     * Creates new form MainDesktop
     */
    public MainDesktop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        contactsMenu = new javax.swing.JMenu();
        contactListMenu = new javax.swing.JMenuItem();
        contactAddMenu = new javax.swing.JMenuItem();
        messageMenu = new javax.swing.JMenu();
        messageListMenu = new javax.swing.JMenuItem();
        messageSendMenu = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de mensagens");

        contactsMenu.setMnemonic('e');
        contactsMenu.setText("Contatos");

        contactListMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        contactListMenu.setMnemonic('t');
        contactListMenu.setText("Listagem");
        contactListMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactListMenuActionPerformed(evt);
            }
        });
        contactsMenu.add(contactListMenu);

        contactAddMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        contactAddMenu.setMnemonic('y');
        contactAddMenu.setText("Adicionar");
        contactAddMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactAddMenuActionPerformed(evt);
            }
        });
        contactsMenu.add(contactAddMenu);

        menuBar.add(contactsMenu);

        messageMenu.setMnemonic('h');
        messageMenu.setText("Mensagens");
        messageMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageMenuActionPerformed(evt);
            }
        });

        messageListMenu.setMnemonic('c');
        messageListMenu.setText("Listagem");
        messageListMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageListMenuActionPerformed(evt);
            }
        });
        messageMenu.add(messageListMenu);

        messageSendMenu.setMnemonic('a');
        messageSendMenu.setText("Adicionar");
        messageSendMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageSendMenuActionPerformed(evt);
            }
        });
        messageMenu.add(messageSendMenu);

        menuBar.add(messageMenu);

        jMenu1.setText("Sair");
        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1017, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void messageSendMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageSendMenuActionPerformed
        // TODO add your handling code here:
        MessageSendForm messageSend = new MessageSendForm();
        desktopPane.add(messageSend);
        messageSend.pack();
        messageSend.setVisible(true);
        
    }//GEN-LAST:event_messageSendMenuActionPerformed

    private void contactAddMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactAddMenuActionPerformed
        ContactAddForm contactAdd = new ContactAddForm();
        desktopPane.add(contactAdd);
        contactAdd.pack();
        contactAdd.setVisible(true);

    }//GEN-LAST:event_contactAddMenuActionPerformed

    private void contactListMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactListMenuActionPerformed
        ContactListForm contactListForm = new ContactListForm(this);
        desktopPane.add(contactListForm);
        contactListForm.pack();
        contactListForm.setVisible(true);
    }//GEN-LAST:event_contactListMenuActionPerformed

    private void messageListMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageListMenuActionPerformed
        // TODO add your handling code here:
        MessageListForm messageListForm = new MessageListForm();
        desktopPane.add(messageListForm);
        messageListForm.pack();
        messageListForm.setVisible(true);
    }//GEN-LAST:event_messageListMenuActionPerformed

    private void messageMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageMenuActionPerformed

    public void contactUpdateMenuActionPerformed(Contact contact) {
        ContactUpdateForm contactUpdateForm = new ContactUpdateForm(contact);
        desktopPane.add(contactUpdateForm);
        contactUpdateForm.pack();
        contactUpdateForm.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDesktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem contactAddMenu;
    private javax.swing.JMenuItem contactListMenu;
    private javax.swing.JMenu contactsMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem messageListMenu;
    private javax.swing.JMenu messageMenu;
    private javax.swing.JMenuItem messageSendMenu;
    // End of variables declaration//GEN-END:variables

}
